---
exclude: '^(src/mostlyai/qa/assets)/'
repos:
- repo: local
  hooks:
    - id: generate-license-header
      name: Generate temporary license header file
      entry: |
        bash -c '
        HEADER_CONTENT="Copyright 2024 MOSTLY AI\n\
        \n\
        Licensed under the Apache License, Version 2.0 (the \"License\");\n\
        you may not use this file except in compliance with the License.\n\
        You may obtain a copy of the License at\n\
        \n\
            http://www.apache.org/licenses/LICENSE-2.0\n\
        \n\
        Unless required by applicable law or agreed to in writing, software\n\
        distributed under the License is distributed on an \"AS IS\" BASIS,\n\
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n\
        See the License for the specific language governing permissions and\n\
        limitations under the License."

        echo -e "$HEADER_CONTENT" > LICENSE_HEADER
        '
      language: system
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
    - id: insert-license
      files: \.py$
      args:
        # - --remove-header
        - --license-filepath
        - LICENSE_HEADER
        - --use-current-year
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-json
    - id: mixed-line-ending
      args: [--fix=lf]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.4
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v3.0.2
  hooks:
  - id: prettier
    entry: prettier --write --list-different --ignore-unknown
    types: [markdown]
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
  - id: codespell
    name: codespell
    description: Checks for common misspellings in text files.
    entry: codespell -w
    language: python
    types: [markdown]
